### ISSUE TITLE
 ErrorUtilTest.testFullExceptionDetails and ErrorUtilTest.testStackTraceString failing

### ISSUE THREAD

**Issue by rajeshmohanan** [ExpediaDotCom/adaptive-alerting#607]
I just downloaded the latest from git and tried to build but got the following error message:

[ERROR] Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! - in com.expedia.adaptivealerting.anomdetect.util.ErrorUtilTest
[ERROR] testFullExceptionDetails(com.expedia.adaptivealerting.anomdetect.util.ErrorUtilTest)  Time elapsed: 0.001 s  <<< FAILURE!
java.lang.AssertionError
        at com.expedia.adaptivealerting.anomdetect.util.ErrorUtilTest.testFullExceptionDetails(ErrorUtilTest.java:30)

[ERROR] testStackTraceString(com.expedia.adaptivealerting.anomdetect.util.ErrorUtilTest)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError
        at com.expedia.adaptivealerting.anomdetect.util.ErrorUtilTest.testStackTraceString(ErrorUtilTest.java:42)

....
2019-10-23 13:45:09 ERROR ReflectionUtil:32 - Error instantiating com.expedia.adaptivealerting.anomdetect.detect.AnomalyThresholds
java.lang.InstantiationException: com.expedia.adaptivealerting.anomdetect.detect.AnomalyThresholds
        at java.lang.Class.newInstance(Class.java:427)
        at com.expedia.adaptivealerting.anomdetect.util.ReflectionUtil.newInstance(ReflectionUtil.java:30)
        at com.expedia.adaptivealerting.anomdetect.util.ReflectionUtilTest.testNewInstance_instantiationException(ReflectionUtilTest.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

....
[ERROR] Failures:
[ERROR]   ErrorUtilTest.testFullExceptionDetails:30
[ERROR]   ErrorUtilTest.testStackTraceString:42
[INFO]
[ERROR] Tests run: 212, Failures: 2, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for com.expedia.adaptivealerting:adaptive-alerting 1.0.0-SNAPSHOT:
[INFO]
[INFO] com.expedia.adaptivealerting:adaptive-alerting ..... SUCCESS [  2.078 s]
[INFO] com.expedia.adaptivealerting:adaptive-alerting-anomdetect FAILURE [ 34.549 s]
[INFO] com.expedia.adaptivealerting:adaptive-alerting-metrics SKIPPED
[INFO] com.expedia.adaptivealerting:adaptive-alerting-metricprofiler SKIPPED
[INFO] com.expedia.adaptivealerting:adaptive-alerting-kafka SKIPPED
[INFO] com.expedia.adaptivealerting:adaptive-alerting-modelservice SKIPPED
[INFO] com.expedia.adaptivealerting:adaptive-alerting-reporting SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by sumitanvekar** [comment]
I tried it today and it seemed to build ok. I used `$ ./mvnw clean verify` as recommended in documentation.
